title: 墨翎の博客
author: Morin
language: zh-CN
timezone: Asia/Shanghai
url: https://blog.rin-tery.fyi
root: /
permalink: :year/:month/:day/:title/
theme: hsad

# highlight
syntax_highlighter: prismjs

prismjs:
  preprocess: true
  line_number: false
  tab_replace: '  '
